services:
  larc-pdf-api:
    build: .
    container_name: larc-pdf-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PDF_MAX_FILE_SIZE_MB=10
      - PDF_UPLOADS_FOLDER=uploads
      - PDF_FONTS_FOLDER=Fonts
      - PDF_DEFAULT_FONT_SIZE=16
    volumes:
      - ./uploads:/app/uploads
      - ./Fonts:/app/Fonts
