/**
 * BarcodeAPI | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BarcodeByIdGetIdParameter } from './barcodeByIdGetIdParameter';


export interface StringSegment { 
    buffer?: string | null;
    offset?: BarcodeByIdGetIdParameter;
    length?: BarcodeByIdGetIdParameter;
    value?: string | null;
    hasValue?: boolean;
}

